Fix separation of columns
CartoDB/odbc_fdw pull request #129
Opened 2020-10-21 15:35 UTC by jgoizueta

The comma-separation of columns was incorrect if the first column was skipped due to unsupported type (so a leading coman would appear: `,col1,col2`.

2020-10-21 15:43 UTC, Algunenano requested changes
I'm missing tests, not only on this change but also on other recent changes in the project.

2020-10-23 06:58 UTC, jgoizueta commented
I'm preparing a test for this case, which seems easy, but for other ongoing changes I'm missing C-level unit tests. @Algunenano any advice how to approach them given your experience with PostGIS?

2020-10-23 08:03 UTC, Algunenano commented
> any advice on how to approach them given your experience with PostGIS?

What we do is we generate a static C library that doesn't depend on Postgresql and test that with unit tests, and then the final library is generated using that library and the files that depend on Postgres to generate the final .so that is distributed.

2020-10-26 08:56 UTC, jgoizueta commented
I could not a test with the pg fdw as I intended, since there is not pg we ignore, so I had to add a test for sql server. Tests for sql server are currently disabled in CI, so I ran it manually and, believe me, it succeeded. I'll open a separate ticket to enable back the sql server tests using the docker I used to run the test locally, but I'll leave this PR with the disabled new test.

2020-10-26 08:58 UTC, Algunenano approved these changes
Thanks for the extra effort!

2020-10-29 12:28 UTC, jgoizueta commented
OK, I had forgotten the disabled sql server tests runs on AppVeyor, and it has revealed a bug which wasn't observed in my sql server tests (which ran on linux). The bug, which should be fixed by #e863ad1 was causing in this case the IMPORT FOREIGN SCHEMA to not import all remotes tables (the tables loop was terminated too early because the variable that controls it was being reused inside the loop.

2020-10-30 07:16 UTC, merged